# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'страны',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(help_text='Возьмите из Яндекс карт', verbose_name='Долгота')),
                ('latitude', models.FloatField(help_text='Возьмите из Яндекс карт', verbose_name='Широта')),
                ('fulladdress', models.CharField(help_text='В формате "ул. Московская, д.9"', max_length=500, unique=True, verbose_name='Адрес')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.City')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Country')),
            ],
            options={
                'verbose_name': 'область',
                'verbose_name_plural': 'области',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Region'),
        ),
    ]
