# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('admin_description', models.CharField(blank=True, max_length=200, verbose_name='Примечания для админов')),
                ('phone', utils.fields.PhoneField(blank=True, max_length=128, verbose_name='Телефон')),
                ('max_players', models.IntegerField(default=0, verbose_name='Максимальное количество игроков')),
                ('cost', models.IntegerField(default=0, verbose_name='Стоимость аренды, RUB/час')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='courts', verbose_name='Изображение')),
                ('views', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'площадка',
                'ordering': ['-views'],
                'verbose_name_plural': 'площадки',
            },
        ),
        migrations.CreateModel(
            name='CourtType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название типа площадки')),
            ],
            options={
                'verbose_name': 'тип площадки',
                'verbose_name_plural': 'типы площадок',
            },
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название типа покрытия')),
            ],
            options={
                'verbose_name': 'тип покрытия',
                'verbose_name_plural': 'типы покрытий',
            },
        ),
        migrations.CreateModel(
            name='Worktime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timefrom', models.TimeField(verbose_name='Начало работы')),
                ('timeto', models.TimeField(verbose_name='Конец работы')),
            ],
        ),
        migrations.AddField(
            model_name='court',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courts.CourtType', verbose_name='Тип площадки'),
        ),
    ]
