# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amplua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'амплуа',
                'verbose_name_plural': 'амплуа',
            },
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название типа игры')),
            ],
            options={
                'verbose_name': 'Тип игры',
                'verbose_name_plural': 'Типы игры',
            },
        ),
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название вида спорта')),
            ],
            options={
                'verbose_name': 'Вид спорта',
                'verbose_name_plural': 'Виды спорта',
            },
        ),
        migrations.AddField(
            model_name='gametype',
            name='sporttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.SportType', verbose_name='Вид спорта'),
        ),
        migrations.AddField(
            model_name='amplua',
            name='sporttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sports.SportType', verbose_name='Вид спорта'),
        ),
    ]
