# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courts', '0001_initial'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=True, help_text='Делает видимым в потоке', verbose_name='Публичный статус')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('cost', models.PositiveIntegerField(verbose_name='Цена')),
                ('datetime', models.DateTimeField(verbose_name='Дата проведения')),
                ('datetime_to', models.DateTimeField(blank=True, verbose_name='Дата окончания')),
                ('reserved_count', models.PositiveIntegerField(default=0, verbose_name='Резервных мест')),
                ('deleted', models.BooleanField(default=False, verbose_name='Игра удалена')),
                ('is_reported', models.BooleanField(default=False, verbose_name='Отчет отправлен')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach', to=settings.AUTH_USER_MODEL)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.Court', verbose_name='Площадка')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gametype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.GameType', verbose_name='Тип игры')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('sporttype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sports.SportType', verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Игра',
                'get_latest_by': 'datetime',
                'verbose_name_plural': 'Игры',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='UserGameAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Дата действия')),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'Записался'), (2, 'Отписался'), (3, 'В резерве'), (4, 'Вышел из резерва'), (5, 'Посетил'), (6, 'Не пришел'), (7, 'Не заплатил')], verbose_name='Действие')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'записи на игру',
                'verbose_name': 'запись на игру',
            },
        ),
    ]
