# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 18:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Время')),
                ('text', models.TextField(verbose_name='Текст')),
                ('read', models.PositiveSmallIntegerField(choices=[(0, 'Новое'), (1, 'Прочитаное'), (2, 'Удаленное')], default=0, verbose_name='Статус')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Информация'), (1, 'Обратите внимание'), (2, 'Внимание')], default=0, verbose_name='Уровень уведомления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'get_latest_by': 'datetime',
                'ordering': ['-datetime'],
            },
        ),
    ]
